; Stinol 102L Smart Refrigerator Controller v1 (Simple)
[platformio]
default_envs = esp8266

[env:esp8266]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m3m.ld
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.12.2
    marvinroger/AsyncMqttClient@^0.9.0
    me-no-dev/ESPAsyncWebServer@^3.1.7
    me-no-dev/ESPAsyncTCP@^1.2.2
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^7.2.0
build_flags =
    -DPLATFORM_ESP8266
